import { useEffect, useState } from "react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { useLanguage } from "@/contexts/LanguageContext";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Mail, Bell, Loader2, Save, Database, Trash2, Play, Image as ImageIcon, CheckCircle2, AlertCircle } from "lucide-react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import DbHealthPanel from "@/components/admin/DbHealthPanel";

interface EmailState {
  id: number;
  batch_size: number;
  send_delay_ms: number;
  auth_email_ttl_minutes: number;
  transactional_email_ttl_minutes: number;
}

interface CleanupSettings {
  retention_days: number;
  enabled: boolean;
  last_run_at: string | null;
  last_deleted_count: number;
  last_run_by: string | null;
  last_run_status: string;
  last_run_error: string | null;
  media_enabled: boolean;
  media_retention_days: number;
  media_last_run_at: string | null;
  media_last_deleted_count: number;
  media_last_run_by: string | null;
  media_last_run_status: string;
  media_last_run_error: string | null;
}

const SystemSettingsPage = () => {
  const { t, language } = useLanguage();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [state, setState] = useState<EmailState | null>(null);

  const [cleanup, setCleanup] = useState<CleanupSettings | null>(null);
  const [cleanupLoading, setCleanupLoading] = useState(true);
  const [cleanupSaving, setCleanupSaving] = useState(false);
  const [runningNow, setRunningNow] = useState(false);
  const [runningMediaNow, setRunningMediaNow] = useState(false);
  const [runnerNames, setRunnerNames] = useState<Record<string, string>>({});
  const [confirmKind, setConfirmKind] = useState<null | "schedule" | "media">(null);
  const [runResult, setRunResult] = useState<
    null | { kind: "schedule" | "media"; success: boolean; deleted: number; error?: string; at: string }
  >(null);

  const labels = {
    title: { zh: "系統設定", en: "System Settings", ja: "システム設定" },
    subtitle: { zh: "管理郵件佇列、通知與系統層級參數", en: "Manage email queue, notifications and system-level parameters", ja: "メールキュー、通知、システムレベルのパラメータを管理" },
    emailTab: { zh: "郵件設定", en: "Email", ja: "メール設定" },
    notifTab: { zh: "通知設定", en: "Notifications", ja: "通知設定" },
    queueTitle: { zh: "郵件佇列參數", en: "Email Queue Parameters", ja: "メールキューのパラメータ" },
    queueDesc: { zh: "調整郵件發送速率與超時設定，影響全系統郵件流量。", en: "Adjust email send rate and TTL. Affects all outgoing email throughput.", ja: "メール送信レートとTTLを調整。すべての送信メールに影響。" },
    batchSize: { zh: "每次批量大小 (batch_size)", en: "Batch size", ja: "バッチサイズ" },
    delay: { zh: "間隔毫秒 (send_delay_ms)", en: "Delay (ms)", ja: "遅延 (ms)" },
    authTtl: { zh: "Auth 郵件 TTL (分鐘)", en: "Auth email TTL (minutes)", ja: "認証メールTTL（分）" },
    txTtl: { zh: "交易郵件 TTL (分鐘)", en: "Transactional email TTL (minutes)", ja: "トランザクションメールTTL（分）" },
    save: { zh: "儲存設定", en: "Save", ja: "保存" },
    saved: { zh: "已儲存", en: "Saved", ja: "保存しました" },
    error: { zh: "儲存失敗", en: "Save failed", ja: "保存に失敗しました" },
    notifTitle: { zh: "通知設定", en: "Notifications", ja: "通知設定" },
    notifDesc: { zh: "目前通知由系統自動產生（授權到期、客服訊息等）。後續可在此擴充偏好設定。", en: "Notifications are currently auto-generated by the system (license expiry, CS messages, etc.). Preferences will be added here later.", ja: "通知は現在システムによって自動生成されます。今後ここで設定を拡張予定です。" },
    dbTab: { zh: "資料庫健康", en: "DB Health", ja: "DB 健全性" },
    cleanupTab: { zh: "排程清除", en: "Schedule Cleanup", ja: "スケジュール削除" },
    cleanupTitle: { zh: "排程自動清除設定", en: "Auto Schedule Cleanup", ja: "スケジュール自動削除" },
    cleanupDesc: {
      zh: "設定排程結束後保留天數，超過時間將永久刪除（不影響播放紀錄）。每日 03:15 UTC 自動執行。",
      en: "Configure how many days to keep finished schedule blocks. Expired ones will be permanently deleted (playback logs are kept). Runs daily at 03:15 UTC.",
      ja: "終了したスケジュールの保持日数を設定します。期限切れは永久削除されます（再生ログは保持）。毎日03:15 UTCに実行。",
    },
    retentionDays: { zh: "保留天數", en: "Retention days", ja: "保持日数" },
    cleanupEnabled: { zh: "啟用自動清除", en: "Enable auto cleanup", ja: "自動削除を有効化" },
    lastRun: { zh: "最近一次執行", en: "Last run", ja: "前回の実行" },
    lastDeleted: { zh: "最近清除筆數", en: "Last deleted", ja: "前回削除件数" },
    never: { zh: "尚未執行", en: "Never", ja: "未実行" },
    runNow: { zh: "立即執行清除", en: "Run cleanup now", ja: "今すぐ実行" },
    runSuccess: { zh: "已清除 {n} 筆過期排程", en: "Deleted {n} expired schedule(s)", ja: "{n}件の期限切れを削除しました" },
    runFailed: { zh: "執行失敗", en: "Run failed", ja: "実行失敗" },
    mediaCleanupTitle: { zh: "未使用媒體自動清除", en: "Unused Media Auto Cleanup", ja: "未使用メディアの自動削除" },
    mediaCleanupDesc: {
      zh: "刪除超過指定天數未被使用之圖片與影片。未使用是指：未綁定設計專案、未在頻道排程或事件觸發、未作為頻道 BGM。系統內建素材不會被刪除。",
      en: "Delete images/videos unused for the specified number of days. Unused means: not bound to any design project, not in channel schedules or smart triggers, and not used as channel BGM. System assets are never removed.",
      ja: "指定日数以上未使用の画像/動画を削除します。未使用とは：デザインプロジェクト未紐付け、チャンネルスケジュールやスマートトリガー未使用、BGM未使用。システム素材は削除されません。",
    },
    mediaRetentionDays: { zh: "未使用保留天數", en: "Unused retention days", ja: "未使用の保持日数" },
    mediaCleanupEnabled: { zh: "啟用媒體自動清除", en: "Enable media auto cleanup", ja: "メディア自動削除を有効化" },
    runMediaNow: { zh: "立即清除未使用媒體", en: "Run media cleanup now", ja: "今すぐメディアを削除" },
    runMediaSuccess: { zh: "已清除 {n} 筆未使用媒體", en: "Deleted {n} unused media item(s)", ja: "{n}件の未使用メディアを削除しました" },
    lastRunBy: { zh: "執行者", en: "Executed by", ja: "実行者" },
    statusLabel: { zh: "上次狀態", en: "Last status", ja: "前回の状態" },
    statusSuccess: { zh: "成功", en: "Success", ja: "成功" },
    statusFailed: { zh: "失敗", en: "Failed", ja: "失敗" },
    statusIdle: { zh: "尚未執行", en: "Not run yet", ja: "未実行" },
    systemRunner: { zh: "系統自動執行", en: "System (cron)", ja: "システム自動" },
    unknownUser: { zh: "未知使用者", en: "Unknown user", ja: "不明なユーザー" },
    confirmTitle: { zh: "確認執行清除？", en: "Run cleanup now?", ja: "クリーンアップを実行しますか？" },
    confirmScheduleDesc: {
      zh: "此操作將立即永久刪除超過保留天數的過期排程。已產生的播放紀錄不受影響，但排程資料無法復原。",
      en: "This will immediately and permanently delete expired schedule blocks beyond the retention window. Playback logs are kept, but schedule data cannot be recovered.",
      ja: "保持期間を超えた期限切れスケジュールを直ちに永久削除します。再生ログは残りますが、スケジュールデータは復元できません。",
    },
    confirmMediaDesc: {
      zh: "此操作將立即永久刪除超過保留天數且未被任何排程、設計專案、BGM 或觸發器使用的圖片與影片。檔案無法復原。",
      en: "This will immediately and permanently delete images and videos beyond the retention window that are not used by any schedule, design project, BGM, or trigger. Files cannot be recovered.",
      ja: "保持期間を超え、スケジュール・デザインプロジェクト・BGM・トリガーで未使用の画像と動画を直ちに永久削除します。復元できません。",
    },
    confirmRun: { zh: "確認執行", en: "Run now", ja: "実行する" },
    cancel: { zh: "取消", en: "Cancel", ja: "キャンセル" },
    resultTitle: { zh: "本次執行結果", en: "Latest run result", ja: "今回の実行結果" },
    resultAt: { zh: "完成時間", en: "Completed at", ja: "完了時刻" },
    resultDeleted: { zh: "刪除筆數", en: "Deleted count", ja: "削除件数" },
    resultKindSchedule: { zh: "排程清除", en: "Schedule cleanup", ja: "スケジュール削除" },
    resultKindMedia: { zh: "未使用媒體清除", en: "Unused media cleanup", ja: "未使用メディア削除" },
    dismiss: { zh: "關閉", en: "Dismiss", ja: "閉じる" },
  };
  const L = (k: keyof typeof labels) => labels[k][language];

  useEffect(() => {
    (async () => {
      const { data, error } = await supabase
        .from("email_send_state")
        .select("*")
        .eq("id", 1)
        .maybeSingle();
      if (!error && data) setState(data as EmailState);
      setLoading(false);
    })();
  }, []);

  const loadCleanup = async () => {
    setCleanupLoading(true);
    const { data, error } = await supabase
      .from("schedule_cleanup_settings")
      .select(
        "retention_days, enabled, last_run_at, last_deleted_count, last_run_by, last_run_status, last_run_error, media_enabled, media_retention_days, media_last_run_at, media_last_deleted_count, media_last_run_by, media_last_run_status, media_last_run_error",
      )
      .eq("id", 1)
      .maybeSingle();
    if (!error && data) {
      const c = data as CleanupSettings;
      setCleanup(c);
      const ids = Array.from(
        new Set([c.last_run_by, c.media_last_run_by].filter((x): x is string => !!x)),
      );
      if (ids.length > 0) {
        const { data: profs } = await supabase
          .from("profiles")
          .select("user_id, display_name")
          .in("user_id", ids);
        const map: Record<string, string> = {};
        (profs || []).forEach((p: { user_id: string; display_name: string | null }) => {
          map[p.user_id] = p.display_name || labels.unknownUser[language];
        });
        setRunnerNames(map);
      } else {
        setRunnerNames({});
      }
    }
    setCleanupLoading(false);
  };

  useEffect(() => {
    loadCleanup();
  }, []);

  const handleSaveCleanup = async () => {
    if (!cleanup) return;
    setCleanupSaving(true);
    const { data, error } = await supabase.rpc("update_schedule_cleanup_settings", {
      _retention_days: cleanup.retention_days,
      _enabled: cleanup.enabled,
      _media_retention_days: cleanup.media_retention_days,
      _media_enabled: cleanup.media_enabled,
    });
    setCleanupSaving(false);
    const result = data as { success?: boolean; error?: string } | null;
    if (error || !result?.success) {
      toast.error(L("error"));
    } else {
      toast.success(L("saved"));
    }
  };

  const handleRunNow = async () => {
    setRunningNow(true);
    const { data, error } = await supabase.rpc("run_schedule_cleanup_now");
    setRunningNow(false);
    const result = data as { success?: boolean; deleted?: number; error?: string } | null;
    if (error || !result?.success) {
      const msg = error?.message || result?.error || L("runFailed");
      setRunResult({ kind: "schedule", success: false, deleted: 0, error: msg, at: new Date().toISOString() });
      toast.error(L("runFailed"));
      loadCleanup();
      return;
    }
    const n = result.deleted ?? 0;
    setRunResult({ kind: "schedule", success: true, deleted: n, at: new Date().toISOString() });
    toast.success(L("runSuccess").replace("{n}", String(n)));
    loadCleanup();
  };

  const handleRunMediaNow = async () => {
    setRunningMediaNow(true);
    const { data, error } = await supabase.rpc("run_media_cleanup_now");
    setRunningMediaNow(false);
    const result = data as { success?: boolean; deleted?: number; error?: string } | null;
    if (error || !result?.success) {
      const msg = error?.message || result?.error || L("runFailed");
      setRunResult({ kind: "media", success: false, deleted: 0, error: msg, at: new Date().toISOString() });
      toast.error(L("runFailed"));
      loadCleanup();
      return;
    }
    const n = result.deleted ?? 0;
    setRunResult({ kind: "media", success: true, deleted: n, at: new Date().toISOString() });
    toast.success(L("runMediaSuccess").replace("{n}", String(n)));
    loadCleanup();
  };

  const handleSave = async () => {
    if (!state) return;
    setSaving(true);
    const { error } = await supabase
      .from("email_send_state")
      .update({
        batch_size: state.batch_size,
        send_delay_ms: state.send_delay_ms,
        auth_email_ttl_minutes: state.auth_email_ttl_minutes,
        transactional_email_ttl_minutes: state.transactional_email_ttl_minutes,
      })
      .eq("id", 1);
    setSaving(false);
    if (error) {
      toast.error(L("error"));
    } else {
      toast.success(L("saved"));
    }
  };

  return (
    <DashboardLayout>
      <div className="flex flex-col h-full p-6 space-y-4 max-w-6xl">
        <div>
          <h1 className="text-xl font-bold text-foreground">{L("title")}</h1>
          <p className="text-sm text-muted-foreground mt-1">{L("subtitle")}</p>
        </div>

        <Tabs defaultValue="email" className="w-full">
          <TabsList>
            <TabsTrigger value="email"><Mail className="w-4 h-4 mr-1" />{L("emailTab")}</TabsTrigger>
            <TabsTrigger value="notif"><Bell className="w-4 h-4 mr-1" />{L("notifTab")}</TabsTrigger>
            <TabsTrigger value="db"><Database className="w-4 h-4 mr-1" />{L("dbTab")}</TabsTrigger>
            <TabsTrigger value="cleanup"><Trash2 className="w-4 h-4 mr-1" />{L("cleanupTab")}</TabsTrigger>
          </TabsList>

          <TabsContent value="email" className="mt-4">
            <Card>
              <CardHeader>
                <CardTitle>{L("queueTitle")}</CardTitle>
                <CardDescription>{L("queueDesc")}</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {loading ? (
                  <div className="flex justify-center py-10">
                    <Loader2 className="w-6 h-6 animate-spin text-primary" />
                  </div>
                ) : state ? (
                  <>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-1.5">
                        <Label>{L("batchSize")}</Label>
                        <Input
                          type="number"
                          min={1}
                          value={state.batch_size}
                          onChange={(e) => setState({ ...state, batch_size: Number(e.target.value) })}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <Label>{L("delay")}</Label>
                        <Input
                          type="number"
                          min={0}
                          value={state.send_delay_ms}
                          onChange={(e) => setState({ ...state, send_delay_ms: Number(e.target.value) })}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <Label>{L("authTtl")}</Label>
                        <Input
                          type="number"
                          min={1}
                          value={state.auth_email_ttl_minutes}
                          onChange={(e) => setState({ ...state, auth_email_ttl_minutes: Number(e.target.value) })}
                        />
                      </div>
                      <div className="space-y-1.5">
                        <Label>{L("txTtl")}</Label>
                        <Input
                          type="number"
                          min={1}
                          value={state.transactional_email_ttl_minutes}
                          onChange={(e) => setState({ ...state, transactional_email_ttl_minutes: Number(e.target.value) })}
                        />
                      </div>
                    </div>
                    <div className="flex justify-end pt-2">
                      <Button onClick={handleSave} disabled={saving}>
                        {saving ? <Loader2 className="w-4 h-4 mr-1 animate-spin" /> : <Save className="w-4 h-4 mr-1" />}
                        {L("save")}
                      </Button>
                    </div>
                  </>
                ) : null}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="notif" className="mt-4">
            <Card>
              <CardHeader>
                <CardTitle>{L("notifTitle")}</CardTitle>
                <CardDescription>{L("notifDesc")}</CardDescription>
              </CardHeader>
            </Card>
          </TabsContent>

          <TabsContent value="db" className="mt-4">
            <DbHealthPanel />
          </TabsContent>

          <TabsContent value="cleanup" className="mt-4">
            <Card>
              <CardHeader>
                <CardTitle>{L("cleanupTitle")}</CardTitle>
                <CardDescription>{L("cleanupDesc")}</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {cleanupLoading ? (
                  <div className="flex justify-center py-10">
                    <Loader2 className="w-6 h-6 animate-spin text-primary" />
                  </div>
                ) : cleanup ? (
                  <>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-1.5">
                        <Label>{L("retentionDays")}</Label>
                        <Input
                          type="number"
                          min={1}
                          max={3650}
                          value={cleanup.retention_days}
                          onChange={(e) =>
                            setCleanup({ ...cleanup, retention_days: Number(e.target.value) })
                          }
                        />
                      </div>
                      <div className="flex items-center gap-3 pt-6">
                        <Switch
                          checked={cleanup.enabled}
                          onCheckedChange={(v) => setCleanup({ ...cleanup, enabled: v })}
                        />
                        <Label className="cursor-pointer">{L("cleanupEnabled")}</Label>
                      </div>
                    </div>

                    <div className="rounded-md border border-border bg-muted/30 p-4 space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">{L("lastRun")}</span>
                        <span className="font-medium text-foreground">
                          {cleanup.last_run_at
                            ? new Date(cleanup.last_run_at).toLocaleString()
                            : L("never")}
                        </span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">{L("lastDeleted")}</span>
                        <span className="font-medium text-foreground">{cleanup.last_deleted_count}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">{L("lastRunBy")}</span>
                        <span className="font-medium text-foreground">
                          {cleanup.last_run_at
                            ? cleanup.last_run_by
                              ? runnerNames[cleanup.last_run_by] || L("unknownUser")
                              : L("systemRunner")
                            : "—"}
                        </span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">{L("statusLabel")}</span>
                        <span
                          className={
                            cleanup.last_run_status === "success"
                              ? "font-medium text-green-600 dark:text-green-400"
                              : cleanup.last_run_status === "failed"
                                ? "font-medium text-destructive"
                                : "font-medium text-muted-foreground"
                          }
                        >
                          {cleanup.last_run_status === "success"
                            ? L("statusSuccess")
                            : cleanup.last_run_status === "failed"
                              ? `${L("statusFailed")}${cleanup.last_run_error ? `: ${cleanup.last_run_error}` : ""}`
                              : L("statusIdle")}
                        </span>
                      </div>
                    </div>

                    <div className="flex justify-between pt-2 gap-2 flex-wrap">
                      <Button
                        variant="outline"
                        onClick={() => setConfirmKind("schedule")}
                        disabled={runningNow}
                      >
                        {runningNow ? (
                          <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                        ) : (
                          <Play className="w-4 h-4 mr-1" />
                        )}
                        {L("runNow")}
                      </Button>
                      <Button onClick={handleSaveCleanup} disabled={cleanupSaving}>
                        {cleanupSaving ? (
                          <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                        ) : (
                          <Save className="w-4 h-4 mr-1" />
                        )}
                        {L("save")}
                      </Button>
                    </div>
                  </>
                ) : null}
              </CardContent>
            </Card>

            {cleanup && (
              <Card className="mt-4">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <ImageIcon className="w-5 h-5" />
                    {L("mediaCleanupTitle")}
                  </CardTitle>
                  <CardDescription>{L("mediaCleanupDesc")}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label>{L("mediaRetentionDays")}</Label>
                      <Input
                        type="number"
                        min={1}
                        max={3650}
                        value={cleanup.media_retention_days}
                        onChange={(e) =>
                          setCleanup({ ...cleanup, media_retention_days: Number(e.target.value) })
                        }
                      />
                    </div>
                    <div className="flex items-center gap-3 pt-6">
                      <Switch
                        checked={cleanup.media_enabled}
                        onCheckedChange={(v) => setCleanup({ ...cleanup, media_enabled: v })}
                      />
                      <Label className="cursor-pointer">{L("mediaCleanupEnabled")}</Label>
                    </div>
                  </div>

                  <div className="rounded-md border border-border bg-muted/30 p-4 space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">{L("lastRun")}</span>
                      <span className="font-medium text-foreground">
                        {cleanup.media_last_run_at
                          ? new Date(cleanup.media_last_run_at).toLocaleString()
                          : L("never")}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">{L("lastDeleted")}</span>
                      <span className="font-medium text-foreground">
                        {cleanup.media_last_deleted_count}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">{L("lastRunBy")}</span>
                      <span className="font-medium text-foreground">
                        {cleanup.media_last_run_at
                          ? cleanup.media_last_run_by
                            ? runnerNames[cleanup.media_last_run_by] || L("unknownUser")
                            : L("systemRunner")
                          : "—"}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">{L("statusLabel")}</span>
                      <span
                        className={
                          cleanup.media_last_run_status === "success"
                            ? "font-medium text-green-600 dark:text-green-400"
                            : cleanup.media_last_run_status === "failed"
                              ? "font-medium text-destructive"
                              : "font-medium text-muted-foreground"
                        }
                      >
                        {cleanup.media_last_run_status === "success"
                          ? L("statusSuccess")
                          : cleanup.media_last_run_status === "failed"
                            ? `${L("statusFailed")}${cleanup.media_last_run_error ? `: ${cleanup.media_last_run_error}` : ""}`
                            : L("statusIdle")}
                      </span>
                    </div>
                  </div>

                  <div className="flex justify-between pt-2 gap-2 flex-wrap">
                    <Button
                      variant="outline"
                      onClick={() => setConfirmKind("media")}
                      disabled={runningMediaNow}
                    >
                      {runningMediaNow ? (
                        <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                      ) : (
                        <Play className="w-4 h-4 mr-1" />
                      )}
                      {L("runMediaNow")}
                    </Button>
                    <Button onClick={handleSaveCleanup} disabled={cleanupSaving}>
                      {cleanupSaving ? (
                        <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                      ) : (
                        <Save className="w-4 h-4 mr-1" />
                      )}
                      {L("save")}
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )}

            {runResult && (
              <Card
                className={`mt-4 border-2 ${
                  runResult.success
                    ? "border-green-500/50 bg-green-500/5"
                    : "border-destructive/50 bg-destructive/5"
                }`}
              >
                <CardHeader className="pb-3">
                  <CardTitle className="flex items-center justify-between gap-2 text-base">
                    <span className="flex items-center gap-2">
                      {runResult.success ? (
                        <CheckCircle2 className="w-5 h-5 text-green-600 dark:text-green-400" />
                      ) : (
                        <AlertCircle className="w-5 h-5 text-destructive" />
                      )}
                      {L("resultTitle")} ·{" "}
                      {runResult.kind === "schedule"
                        ? L("resultKindSchedule")
                        : L("resultKindMedia")}
                    </span>
                    <Button variant="ghost" size="sm" onClick={() => setRunResult(null)}>
                      {L("dismiss")}
                    </Button>
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-1.5 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">{L("statusLabel")}</span>
                    <span
                      className={
                        runResult.success
                          ? "font-medium text-green-600 dark:text-green-400"
                          : "font-medium text-destructive"
                      }
                    >
                      {runResult.success ? L("statusSuccess") : L("statusFailed")}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">{L("resultDeleted")}</span>
                    <span className="font-medium text-foreground">{runResult.deleted}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">{L("resultAt")}</span>
                    <span className="font-medium text-foreground">
                      {new Date(runResult.at).toLocaleString()}
                    </span>
                  </div>
                  {!runResult.success && runResult.error && (
                    <div className="pt-1 text-destructive break-all">{runResult.error}</div>
                  )}
                </CardContent>
              </Card>
            )}
          </TabsContent>
        </Tabs>
      </div>

      <AlertDialog open={confirmKind !== null} onOpenChange={(o) => !o && setConfirmKind(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{L("confirmTitle")}</AlertDialogTitle>
            <AlertDialogDescription>
              {confirmKind === "media" ? L("confirmMediaDesc") : L("confirmScheduleDesc")}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{L("cancel")}</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                const kind = confirmKind;
                setConfirmKind(null);
                if (kind === "schedule") handleRunNow();
                else if (kind === "media") handleRunMediaNow();
              }}
            >
              {L("confirmRun")}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </DashboardLayout>
  );
};

export default SystemSettingsPage;
