-- Tombstone — superseded by 20260415060155_email_infra.sql
--
-- This migration was historically a byte-identical duplicate of
-- 20260415060155_email_infra.sql. All DDL in that file is idempotent
-- (IF NOT EXISTS / CREATE OR REPLACE / DO blocks that swallow
-- duplicate_object), so the duplicate apply was harmless — but the
-- repeated source-of-truth made the schema hard to reason about.
--
-- The file is kept (rather than deleted) to preserve migration history
-- on already-deployed databases. A new clone will skip the body entirely.
SELECT 1;
